language: ruby
rvm:
  - 2.5.1

addons:
  ssh_known_hosts: ham.codes

install: bundle install

script:
  - bundle exec jekyll build
  - bundle exec htmlproofer --http-status-ignore "0,410,503,999" ./_site
  - ./deploy.sh

deploy:
  provider: s3
  bucket: "devbox-bucket.ham.codes"
  secret_access_key:
    secure: O3TGbIyD4RRLFMQCItn0nNta1dPRZeXt2mD07zZVrQWqqQSGgwzJUX96v+QXhEXmwtt8BKrRB8me5n+yIqG0EYKkzmW0nIWJ0G86A/7hNM0cL0ptYa5mXQ8GrLt31j20VWZsH2rZgHii0eV8QlzSW2V5Bm169Csb4aD6ATXECrQFs49rx+HSdhCmvz346qdKm+ftCY3rYeDQzN/HL4SjECx1STCyKCpsFFv4sLdemYfGQQwlummHWcfcoHEoRBNolGnAvARhC2wdGRpu6BBl/CiKtTP6VwxfWCc53ferlgs9lPZMZU7D3LdkCYwH3j5y56MIqVWC+nFBnQrCYRBPFer6ERygQPcP9zJgi7qkPxpISK3hVIVSh/7CdujNNzMPge6af9N96DUUuoQWsfO9mHi/RaL4I5ZuHV/rTj86BtBtB4JyQzaA/QNvMTmTH/Q8zwppr2g60rNtpIhs8wZ7JWnX+owmDW0xS4qSHMB4rDmnLtU6QibZWHPvldCbF1Zh7aiPoMXVXQyW+e3AXI8SWZXIOUFyuxpCm8YdQUPIqlOXnKMbqcasGM7OrfV7ROfcfx+okUFE+ZIxD84lDMWGbf1lkMJa6b6/gE4ivOgZuNI7dZn07QVgIDJvWKOHFeDtLv/q9Anrl3u2V7Nwr4R05JLUP5kBmovE7G/YVaqquKU=
  access_key_id:
    secure: UvNg436lussMJjXkANVuFj4drhAqvlNga59PlOywYFBTw9phnMZibAGEqxYZ6wF5ru7NykQNa7Zje+Xh8W/OiumfRH2310wmjFrGCj7eP4Hl4U2iARSzi6au6qFbsk2AMfSxaEByk8ovzD2uSmQix6LDKuipk8Cbg/u2g1ESEr8FM01J3BkWsYED+DJz1ZFkKr8ODTT4K/5Y7rd3/j8enflNkGO18P5lwdMSHnoK5qeZDk8biXw/vQGh0XGKeNs4rdvJHIEGaB4BIPIIn6amQu2pQP+SwKybyT0BF/DxVwVRS9tGcVIpn0rcUcxqmiA9HSZd9HHyetKjDvHht5E3Cy26q8ErnU3vbAJNPoUVLfSWkXC3kzWnJCHV87OePh3UenObyJg/09Rh/o0Z9/ByBwZr2OVcjM30Yqns+MwIIKa+XqpBGKbvcUv2WDftqezruPIhfnxOn7MmRaQIA9jb4lZ48sgFkRsE5x0KEQbDyKP2SAEnacycaDIPBxAy3UjmFhkMLjR3q2WaMEUk/OEfGRpb4MuaSOJvVJSxoczSg1twq2S8AWtiWqlv7KAMblvRr0yqDdR0S/Mop1fEymZFUFbEsUAGP0TCKXzViMqS+seToI+bL+MmW2pYOBsoPxM7hYwNx4Gl3v1NKeYBsLTEr1WTju6YmnBhYMO3u0ZfHAU=
  skip_cleanup: true
  region: eu-central-1
  local_dir: _site
  upload-dir: blog

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

addons:
  apt:
    packages:
    - libcurl4-openssl-dev

sudo: false

cache: bundler
